[package]
authors.workspace = true
edition.workspace = true
name = "yarsge-dsp"
version.workspace = true

[dependencies]
yarsge-math.workspace = true

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[lib]
bench = false

[[bench]]
harness = false
name = "bench-dsp"
