[package]
authors.workspace = true
edition.workspace = true
name = "yarsge-sdl"
version.workspace = true

[dependencies]
anyhow = "1.0.28"
env_logger.workspace = true
log.workspace = true
rgb = "0.8.52"
sdl3 = "0.18.0"
yarsge-core.workspace = true
yarsge-dsp.workspace = true
yarsge-math.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.177"

[dependencies.clap]
features = ["derive"]
version = "4.0.0"
