[package]
name = "yarsge-core"
version = "0.1.0"
authors = ["Zachery Gyurkovitz <zgyurkovitz@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.0"
failure = "0.1.1"
boolinator = "2"
derive_more = "0.14"