[package]
name = "yarsge-web"
version = "0.1.0"
authors = ["Skyler Ross <orangesnowfox@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4"

[dependencies.yarsge-core]
path = "../yarsge-core"
